name: stale

on:
  schedule:
    - cron: '0 23 * * SUN-THU'

jobs:
  stale:

    runs-on: ubuntu-latest

    if: github.repository == 'optuna/optuna'
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This message is for normal issue to stale.'
        stale-pr-message: 'This message is for normal PR to stale.'
        close-issue-message: 'This message is for normal issue to be closed.'
        close-pr-message: 'This message is for normal PR to be closed.'
        days-before-issue-stale: 1
        days-before-issue-close: 1
        days-before-pr-stale: 1
        days-before-pr-close: 1
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'no-stale,contribution-welcome'
        exempt-pr-labels: 'no-stale'
        operations-per-run: 1000

  stale-cw:

    runs-on: ubuntu-latest

    if: github.repository == 'optuna/optuna'
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This message is only for CW issue to stale.'
        close-issue-message: 'This message is only for CW issue to be closed.'
        days-before-issue-stale: 1
        days-before-issue-close: 1
        stale-issue-label: 'stale'
        only-issue-labels: 'contribution-welcome'
        exempt-issue-labels: 'no-stale'
        operations-per-run: 1000
